// Generated by CoffeeScript 1.6.3
(function() {
  var aComer, comida, ensalada, masVegetales, muchosVegetales, num, otraEnsalada, todos, vegetales, _i, _j, _k, _len, _len1, _len2, _ref,
    __slice = [].slice;

  vegetales = ["Pepino", "Lechuga", "Tomate", "Aguacate", "Cebolla"];

  num = 1;

  for (_i = 0, _len = vegetales.length; _i < _len; _i++) {
    ensalada = vegetales[_i];
    if (ensalada !== "Tomate") {
      alert("Producto: " + (num++) + " - " + ensalada);
    }
  }

  masVegetales = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = vegetales.length; _j < _len1; _j++) {
      ensalada = vegetales[_j];
      if (ensalada) {
        _results.push(ensalada);
      }
    }
    return _results;
  })();

  for (_j = 0, _len1 = masVegetales.length; _j < _len1; _j++) {
    comida = masVegetales[_j];
    alert("Ahora hay dos " + comida + "s");
  }

  num = 1;

  muchosVegetales = vegetales.slice(0);

  [].splice.apply(muchosVegetales, [5, -1].concat(_ref = ["Repollo", "Berro", "Aceituna"])), _ref;

  for (_k = 0, _len2 = muchosVegetales.length; _k < _len2; _k++) {
    otraEnsalada = muchosVegetales[_k];
    alert("Productos: " + (num++) + " - " + otraEnsalada + "s");
  }

  aComer = function() {
    var primero, resto, segundo;
    primero = arguments[0], segundo = arguments[1], resto = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    alert("Los dos primeros y el resto...");
    alert("De primero " + primero);
    alert("De segundo " + segundo);
    return alert("El resto es: " + resto);
  };

  aComer.apply(null, vegetales);

  todos = function() {
    var resto;
    resto = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return alert("Todos: " + resto);
  };

  todos.apply(null, vegetales);

}).call(this);
