// Generated by CoffeeScript 1.6.3
(function() {
  var apellido, edad, nombre, persona;

  nombre = "Tony";

  persona = true;

  edad = 40;

  if (nombre === "Tony") {
    apellido = "Medrano";
  }

  if (persona === true) {
    alert("Se llama " + nombre + " " + apellido + " y tiene " + edad + " años!");
  }

}).call(this);
