// Generated by CoffeeScript 1.6.3
var gpaCount,
  __slice = [].slice;

gpaCount = function() {
  var ArrayorMap, total;
  ArrayorMap = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  total = ArrayorMap.reduce(function(a, b) {
    return a + b;
  });
  return total / ArrayorMap.length;
};
